framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        providers:
        globals:
            app_name:
                value: 'Chess Teams'
