services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html:delegated
      - var_data:/var/www/html/var
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    ports:
      - "127.0.0.1:18010:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> symfony/mercure-bundle ###
  mercure:
    environment:
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000 https://127.0.0.1:8000 http://localhost:8000 https://localhost:8000 http://127.0.0.1:18010 https://127.0.0.1:18010 http://localhost:18010 https://localhost:18010 http://127.0.0.1:18080 https://127.0.0.1:18080 http://localhost:18080 https://localhost:18080
    ports:
      - "127.0.0.1:18080:80"
###< symfony/mercure-bundle ###

volumes:
  var_data:
