name: Code Style

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-style:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl
    
    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
    
    - name: Run PHP CS Fixer
      run: ./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Apply PHP CS Fixer"

    - name: 'Push changes'
      if: always()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        # N'effectue le push que s'il y a des commits en avance
        if [ -n "$(git log @{u}.. 2>/dev/null)" ]; then
          git push "https://${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
        else
          echo "Nothing to push"
        fi